# Generated by Django 3.0.6 on 2020-05-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
